name: 'Automatic build'

# You can specify the default permissions granted to the GITHUB_TOKEN
# for this workflow by adding the permissions key.
# This ensures that your workflow has the necessary access to the repository.
permissions:
  contents: write # This gives the workflow write access to the repository contents.
  # Add more permissions here if needed, e.g., packages: write, issues: write, etc.

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (00:00 UTC)
    
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Deploy
        run: bash deploy.sh
